// ============================================================
//   N E X U S - B O T  |  AI Commands (OpenAI GPT)
// ============================================================

const { OpenAI } = require('openai');
const config = require('../config');
const { sendWithImage } = require('./utils');

function getOpenAI() {
  if (!config.openaiKey || config.openaiKey === 'your_openai_api_key_here') {
    throw new Error('OpenAI API key not configured. Please set OPENAI_API_KEY in your .env file.');
  }
  return new OpenAI({ apiKey: config.openaiKey });
}

// ── ASK AI ──────────────────────────────────────────────────
async function askAI({ sock, msg, jid, q }) {
  if (!q) {
    return sendWithImage(sock, jid, '🤖 *Usage:* `.ai <your question>`\n\n_Example: `.ai What is quantum physics?`_', msg);
  }

  const openai = getOpenAI();
  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: `You are NexusBot, a smart, helpful and slightly witty WhatsApp AI assistant. Keep responses concise and well-formatted for WhatsApp (use *bold* and _italic_ sparingly). Max 400 words.`,
      },
      { role: 'user', content: q },
    ],
    max_tokens: 600,
  });

  const answer = response.choices[0].message.content.trim();
  const text = `🤖 *NexusBot AI*\n\n*Q:* ${q}\n\n*A:* ${answer}`;
  await sendWithImage(sock, jid, text, msg);
}

// ── GENERATE IMAGE ───────────────────────────────────────────
async function generateImage({ sock, msg, jid, q }) {
  if (!q) {
    return sendWithImage(sock, jid, '🎨 *Usage:* `.imagine <description>`\n\n_Example: `.imagine a futuristic city at night`_', msg);
  }

  const openai = getOpenAI();
  await sendWithImage(sock, jid, `🎨 _Generating image for:_ "${q}"...\n\n⏳ Please wait...`, msg);

  const response = await openai.images.generate({
    model: 'dall-e-3',
    prompt: q,
    n: 1,
    size: '1024x1024',
  });

  const imageUrl = response.data[0].url;

  // Send the AI-generated image
  await sock.sendMessage(jid, {
    image: { url: imageUrl },
    caption: `🎨 *AI Generated Image*\n\n*Prompt:* ${q}\n\n_Generated by ${config.botName} × DALL-E 3_`,
  }, { quoted: msg });
}

// ── ROAST ────────────────────────────────────────────────────
async function roast({ sock, msg, jid, q }) {
  if (!q) {
    return sendWithImage(sock, jid, '🔥 *Usage:* `.roast <name or topic>`\n\n_Example: `.roast my Monday morning`_', msg);
  }

  const openai = getOpenAI();
  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: 'You are a savage but funny roast master. Roast the given person or topic in a hilarious, creative way. Keep it witty, not truly hurtful. Max 150 words.',
      },
      { role: 'user', content: `Roast: ${q}` },
    ],
    max_tokens: 250,
  });

  const roastText = response.choices[0].message.content.trim();
  const text = `🔥 *NexusBot Roast Mode* 🔥\n\n_Target:_ *${q}*\n\n${roastText}\n\n😂 _Don't take it personally!_`;
  await sendWithImage(sock, jid, text, msg);
}

// ── JOKE ─────────────────────────────────────────────────────
async function joke({ sock, msg, jid, q }) {
  const openai = getOpenAI();
  const topic = q ? `about: ${q}` : '';
  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: 'You are a comedian. Tell one funny, clean joke. Format: Setup on first line, then "..." then punchline. Max 80 words.',
      },
      { role: 'user', content: `Tell me a joke ${topic}` },
    ],
    max_tokens: 150,
  });

  const jokeText = response.choices[0].message.content.trim();
  const text = `😂 *NexusBot Joke Time!*\n\n${jokeText}`;
  await sendWithImage(sock, jid, text, msg);
}

// ── STORY ────────────────────────────────────────────────────
async function story({ sock, msg, jid, q }) {
  if (!q) {
    return sendWithImage(sock, jid, '📖 *Usage:* `.story <topic>`\n\n_Example: `.story a dragon who hates gold`_', msg);
  }

  const openai = getOpenAI();
  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: 'You are a creative storyteller. Write a short, engaging, creative micro-story (3-4 paragraphs) based on the given topic. Make it vivid and memorable.',
      },
      { role: 'user', content: `Write a short story about: ${q}` },
    ],
    max_tokens: 500,
  });

  const storyText = response.choices[0].message.content.trim();
  const text = `📖 *NexusBot Story: ${q}*\n\n${storyText}\n\n_— Generated by ${config.botName}_`;
  await sendWithImage(sock, jid, text, msg);
}

// ── DEFINE ───────────────────────────────────────────────────
async function define({ sock, msg, jid, q }) {
  if (!q) {
    return sendWithImage(sock, jid, '📚 *Usage:* `.define <word>`\n\n_Example: `.define ephemeral`_', msg);
  }

  const openai = getOpenAI();
  const response = await openai.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content: 'You are a dictionary. Provide: 1) Definition, 2) Part of speech, 3) Example sentence, 4) Fun fact or etymology. Format neatly for WhatsApp.',
      },
      { role: 'user', content: `Define the word: ${q}` },
    ],
    max_tokens: 300,
  });

  const definition = response.choices[0].message.content.trim();
  const text = `📚 *Definition: ${q}*\n\n${definition}`;
  await sendWithImage(sock, jid, text, msg);
}

module.exports = { askAI, generateImage, roast, joke, story, define };
